# Generated by Django 5.2 on 2025-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_remove_product_id_product_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(null=True, upload_to="products/"),
        ),
    ]
