# Generated by Django 5.2 on 2025-05-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_product_image2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discounted_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
