# Generated by Django 5.2 on 2025-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_location_alter_product_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium")],
                default="basic",
                max_length=10,
            ),
        ),
    ]
